# Generated by Django 3.2.6 on 2021-10-07 05:52

from django.db import migrations, models
import phonenumber_field.modelfields
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('bidder_name', models.CharField(max_length=100)),
                ('bidder_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone No')),
            ],
        ),
        migrations.CreateModel(
            name='NaiHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone No.')),
                ('image', models.ImageField(upload_to=properties.models.get_file_path)),
                ('video_links', models.URLField(verbose_name='Video Link')),
                ('description', models.CharField(max_length=225)),
                ('owner_or_broker', models.CharField(choices=[('O', 'OWNER'), ('B', 'BROKER')], max_length=1)),
                ('buy_or_sell', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('bidder_list', models.ManyToManyField(related_name='bidder_list', to='properties.Bid')),
            ],
        ),
    ]
