# Generated by Django 3.2.6 on 2021-10-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_properties_bidder_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='bidder_list',
        ),
        migrations.AddField(
            model_name='bid',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.properties'),
            preserve_default=False,
        ),
    ]
