# Generated by Django 3.2.6 on 2021-10-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20211023_0455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('property_id', 'bidder_phone')},
        ),
    ]
