# Generated by Django 3.2.6 on 2021-10-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_bid_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='video_links',
            field=models.URLField(blank=True, null=True, verbose_name='Video Link'),
        ),
    ]
