# Generated by Django 3.2.6 on 2021-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_properties_video_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='category',
            field=models.CharField(choices=[('2kh', '2_KANAL_HOUSE'), ('1kh', '1_KANAL_HOUSE'), ('4mh', '14_MARLAR_HOUSE'), ('5mh', '5_MARLAR_HOUSE'), ('2kp', '2_KANAL_PLOT'), ('1kp', '1_KANAL_PLOT'), ('4mp', '14_MARLAR_PLOT'), ('5mp', '5_MARLAR_PLOT'), ('5ep', '5_MARLA_EXTENSION_PLOT'), ('5kf', '5_KANAL_FARM')], max_length=3, verbose_name='Properties Type'),
        ),
    ]
