# Generated by Django 3.2.6 on 2021-11-08 05:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_properties_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK', verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='category',
            field=models.CharField(choices=[('2kh', '2_KANAL_HOUSE'), ('1kh', '1_KANAL_HOUSE'), ('4mh', '14_MARLAR_HOUSE'), ('5mh', '5_MARLAR_HOUSE'), ('2kp', '2_KANAL_PLOT'), ('1kp', '1_KANAL_PLOT'), ('4mp', '14_MARLAR_PLOT'), ('5mp', '5_MARLAR_PLOT'), ('5ep', '5_MARLA_EXTENSION_PLOT'), ('5kf', '5_KANAL_FARM'), ('2kc', '2_KANAL_CONSTRUCTION'), ('1kc', '1_KANAL_CONSTRUCTION'), ('5mc', '5_MARLA_CONSTRUCTION'), ('4mc', '14_MARLA_CONSTRUCTION')], max_length=3, verbose_name='Properties Type'),
        ),
    ]
